# FROM k8s.gcr.io/pause-arm64:3.3
# FROM k8s.gcr.io/kube-apiserver-arm64:v1.23.7
# FROM k8s.gcr.io/kube-controller-manager-arm64:v1.23.7
# FROM k8s.gcr.io/kube-scheduler-arm64:v1.23.7
# FROM k8s.gcr.io/kube-proxy-arm64:v1.23.7
FROM k8s.gcr.io/coredns/coredns-arm64:v1.8.6
#FROM k8s.gcr.io/dns/k8s-dns-node-cache-arm64:1.21.1
#FROM k8s.gcr.io/cpa/cluster-proportional-autoscaler-arm64:1.8.5
#FROM k8s.gcr.io/metrics-server/metrics-server-arm64:v0.5.2
