# FROM k8s.gcr.io/pause-arm64:3.3
# FROM k8s.gcr.io/kube-apiserver-arm64:v1.23.7
FROM k8s.gcr.io/kube-controller-manager-arm64:v1.23.7
# FROM k8s.gcr.io/kube-scheduler-arm64:v1.23.7
# FROM k8s.gcr.io/kube-proxy-arm64:v1.23.7
